### ISSUE TITLE
HostPersona Enumeration

### ISSUE THREAD

**Issue by weidi** [equelin/3PAR-Powershell#2]
Hi, 
i stumbled upon that the Host Persona enum is different from the wsapi to the cli. 
What about creating a "translationtable" for all the functions that use persona? I can do this if you want.

**Comment by equelin** [comment]
Hello @weidi 

Thanks for your interest in this module. As you may have seen I did not have the opportunity to work on it because I no longuer have an access to an HPE 3PAR... But I'll be very pleased if you want to open a pull request to add some functionnalities in the module ! 

Thanks,
