### ISSUE TITLE
Error after 3PAR WS API version upgraded

### ISSUE THREAD

**Issue by amaralma** [equelin/3PAR-Powershell#5]
-Service- -State- -HTTP_State- HTTP_Port -HTTPS_State- HTTPS_Port -Version- ------------API_URL-------------
Enabled   Active  Enabled           8008 Enabled             8080 1.5.3     https://<IP>:8080/api/v1

Connect-3PAR $3ParArray -Username $3ParUser -Password $3ParPassword -Verbose
VERBOSE: Validating that login details were passed into username/password or credentials
VERBOSE: Build the URI
VERBOSE: Build the JSON body for Basic Auth
VERBOSE: Submit the session key request
VERBOSE: POST https://<IP>:8080/api/v1/credentials with -1-byte payload
Please verify the connectivity with the array. Retry with the parameter -Verbose for more informations

VERBOSE: Status: SendFailure
VERBOSE: Error code: 
VERBOSE: Message: Unable to read data from the transport connection: An existing connection was forcibly closed by the remot
e host.

Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send.
At line:59 char:25
+ ... ntialdata = Invoke-WebRequest -Uri "$APIurl/credentials" -Body (Conve ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExcepti 
   on
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by equelin** [comment]
Hello,

I'm really sorry but I no longer work with 3PAR arrays... 

You will find the official HPE module here:

https://h20392.www2.hpe.com/portal/swdepot/displayProductInfo.do?productNumber=3PARPSToolkit

Regards,
